### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by stephanepericat**
Done as discussed.

### CODE REVIEW

**Comment by dragoverde** [comment]
1) pom.xml - fix indentation
2) all local widget/container readme files should have the "Additional resources" section listing all additional resources: in this case it's import xml
3) root readme file should include steps 1-3 from usage.txt in the "Configuration" section
4) root readme file: change pf3e1a to pf3e2a

**Comment by stephanepericat** [comment]
@dragoverde changes made as discussed. Please review.

**Comment by dragoverde** [comment]
- <a href="https://github.com/Backbase/training-fe-module-03/blob/v2/cxp-fe-training-03/src/main/webapp/static/cxp-fe-training-03/containers/pf3e4-accordion/js/accordion.js#L23">accordion.js</a>: cxp_training -> cxp_fe_training_03
- please reverse the order of Additional Resources for all containers
- many files still have indentation problems

**Comment by stephanepericat** [comment]
@dragoverde 

 - accordion.js is fixed
 - resources are reversed

For indentation problems, there is not much I can do... different files written by different people with different indentation settings on different operating systems... Can you please point to a few specific files that you absolutely want to see indented properly ?

**Comment by stephanepericat** [comment]
@dragoverde fix indentation for all js and soy files

**Pull request merged**
